name: Bug report for the Medusa Next.js Starter
description: File a bug report.
title: "[Bug]: "
labels: ["status: needs triaging", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## System information
        The system information will help us reproduce the issue in the same environment.
  - type: textarea
    attributes:
      label: Package.json file
      description: Copy/paste the contents of your `package.json` file.
      placeholder: Paste the raw contents of package.json (no backticks needed).
      render: json
    validations:
      required: true
  - type: input
    attributes:
      label: Node.js version
      description: Output of the `node -v` command.
      placeholder: v21.0.0
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system name and version
      description: Example: macOS Ventura 13.4, Ubuntu 22.04, Windows 11
      placeholder: e.g., Ubuntu 22.04
    validations:
      required: true
  - type: input
    attributes:
      label: Browser name
      description: Optional. Example: Chrome, Firefox, Safari
      placeholder: e.g., Chrome 123
  - type: markdown
    attributes:
      value: |
        ## Describe the issue
        Provide a detailed explanation of the problem along with screenshots or code snippets if possible.
  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
      placeholder: I expected it to...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: Describe what actually happened.
      placeholder: Instead, this happened...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Reproduction
        If possible, share a minimal reproduction repo that we can use to replicate the issue.
  - type: input
    attributes:
      label: Link to reproduction repo
      description: Provide a link to a public GitHub repo showing the issue.
      placeholder: https://github.com/your-repo
    validations:
      required: true